### ISSUE TITLE
회의날짜 정하기

### ISSUE THREAD

**Issue by idean3885** [DevaChip/EvaWeather#1]
이런 기능이 있었군요.

**Comment by geuning2** [comment]
회의잡으세요

**Comment by geuning2** [comment]
> 이런 기능이 있었군요.

저런기능

**Comment by geuning2** [comment]
https://github.com/DevaChip/EvaWeather/issues/1#issue-710010916

이 이슈를 확인하세요 그리고 회의 날짜를 잡으세요

**Comment by idean3885** [comment]
ㅋㅋㅋㅋㅋ 추석 끝나고가 될거같습니다.
